config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "machines#index"
  resources :machines
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/machine.rb
class Machine < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :user
  # has_one :reservation
  has_one_attached :image
  belongs_to :status

  with_options presence: true do
    validates :name
    validates :detail
    validates :image
  end
end

app/models/status.rb
class Status < ActiveHash::Base
  self.data = [
    { id: 1, name: '空' },
    { id: 2, name: '満' }
  ]

  include ActiveHash::Associations
  has_many :machines
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  with_options presence: true do
    validates :nickname
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
    validates :email, format: { with: VALID_EMAIL_REGEX }, allow_blank: true
    VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]{6,100}\z/i.freeze
    validates :password, format: { with: VALID_PASSWORD_REGEX }, allow_blank: true
    validates :last_name, format: { with: /\A(?:\p{Hiragana}|\p{Katakana}|[ー－]|[一-龠々])+\z/, allow_blank: true }
    validates :first_name, format: { with: /\A(?:\p{Hiragana}|\p{Katakana}|[ー－]|[一-龠々])+\z/, allow_blank: true }
  end

  has_many :machines
  # has_many :reservations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV['BASIC_AUTH_USER'] && password == ENV['BASIC_AUTH_PASSWORD']
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :last_name, :first_name])
  end
end

app/controllers/machines_controller.rb
class MachinesController < ApplicationController
  before_action :machine_find, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit]

  def index
    @machines = Machine.all.order('created_at DESC').includes(:user)
  end

  def new
    redirect_to root_path if current_user.id != 1
    @machine = Machine.new
  end

  def create
    @machine = Machine.new(machine_params)
    if @machine.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
  end

  def edit
    if (current_user.id != 1 && @machine.status_id == 1) || (current_user.id != 1 && @machine.subscriber.present? && @machine.subscriber != current_user.nickname)
      redirect_to root_path 
    end
  end

  def update
    if @machine.update(machine_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    if current_user.id == 1
      @machine .destroy
      redirect_to root_path
    end
  end

  private

  def machine_params
    params.require(:machine).permit(:name, :detail, :status_id, :time, :subscriber, :checked, :image).merge(user_id: current_user.id)
  end

  def machine_find
    @machine = Machine.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/machines_helper.rb
module MachinesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MachineWatch</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/machines/edit.html.erb
<%# cssは新規マシン登録のものを併用しています。
app/assets/stylesheets/machines/new.css %>

<div class="new-items-contents">
  <header class="new-items-header">
    <%= link_to image_tag('maseen-logo-02.png' , size: '185x50'), "/" %>
  </header>
  <div class="new-items-main">
    <h2 class="newitems-title">マシンの情報を入力</h2>
    <%= form_with model: @machine, url: machine_path, local: true do |f| %>

    <%= render 'shared/error_messages', model: f.object %>

    <%# マシン画像 %>
    <% if user_signed_in? && current_user.id == 1 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        マシン画像
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"item-image" %>
      </div>
    </div>
    <% end %>
    <%# /マシン画像 %>

    <%# マシン名とマシン詳細 %>
    <div class="new-items">
    <% if user_signed_in? && current_user.id == 1 %>
      <div class="weight-bold-text">
        マシン名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :name, class:"items-text", id:"item-name", placeholder:"マシン名（必須 40文字まで)", maxlength:"40" %>

      <div class="weight-bold-text">
        マシンの空き状況
      </div>
      <%= f.collection_select(:status_id, Status.all, :id, :name, {}, {class:"select-box", id:"machine-status"}) %>

      <div class="weight-bold-text">
        利用終了予定時刻
      </div>
      <%= f.text_area :time, class:"items-text", id:"item-name", value: (Time.now + 1200).strftime('%H:%M') %>

      <div class="items-explain">
        <div class="weight-bold-text">
          マシンの説明
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :detail, class:"items-text", id:"item-info", placeholder:"商品の説明（必須 1,000文字まで）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。" ,rows:"7" ,maxlength:"1000" %>
      </div>

      <div class="weight-bold-text">
        予約者
      </div>
      <%= f.text_area :subscriber, class:"items-text",  value: @machine.subscriber, maxlength:"40" %>
      <% end %>

      <% if user_signed_in? && current_user.id != 1 %>
        <% if @machine.subscriber.blank? %>
          <div class="weight-bold-text">
            予約者
          </div>
          <%= f.text_area :subscriber, class:"items-text",  value: current_user.nickname, maxlength:"40" %>
        <% elsif @machine.subscriber.present? && @machine.subscriber == current_user.nickname %>
          <%= f.text_area :subscriber, class:"items-text-delete",  value: "", maxlength:"40" %>
        <% end %>
      <% end %>
    </div>

    <%# /マシン名とマシン詳細 %>

    <%# 下部ボタン %>
    <% if user_signed_in? && current_user.id == 1 %>
      <div class="sell-btn-contents">
        <%= f.submit "変更する" ,class:"sell-btn" %>
        <%=link_to 'もどる', root_path, method: :get, class:"back-btn" %>
      </div>
    <% end %>

    <% if user_signed_in? && current_user.id != 1 %>
      <% if @machine.subscriber != current_user.nickname %>
        <div class="sell-btn-contents">
          <%= f.submit "予約する" ,class:"sell-btn" %>
          <%=link_to 'もどる', root_path, method: :get, class:"back-btn" %>
        </div>
        <% elsif @machine.subscriber == current_user.nickname %>
        <div class="sell-btn-contents">
          <%= f.submit "予約を取り消す" ,class:"sell-btn" %>
          <%=link_to 'もどる', root_path, method: :get, class:"back-btn" %>
        </div>
      <% end %>
    <% end %>
    <%# /下部ボタン %>
  </div>
  <% end %>

  <footer class="new-items-footer">
  </footer>
</div>

app/views/machines/index.html.erb
<%= render "shared/header" %>
<div class='main'>

  <%# 画面上部の帯部分 %>
  <div class='title-contents'>
    <h2 class='service-title'>
      もうトレーニングを待たなくていい
    </h2>
    <p class='service-explain'>
      MaSeenはジム全てのマシンの空き情報を
    </p>
    <p class='service-explain'>
      リアルタイムでお知らせします
    </p>
  </div>
  <%# /画面上部の帯部分  %>

  <%# MaSeenを使う3つのSTEP部分 %>
  <div class='use-step-contents'>
    <h2 class='title'>
      MaSeenを使う3つのSTEP
    </h2>
    <ul class='step-lists'>
      <li class='list'>
        <%= image_tag "step01.jpg", class:"list-pict" %>
        <span class='step-list-number'>1</span>
        <h3 class='step-list-text'>
          空き情報チェック
        </h3>
        <p class='step-list-description'>
          使いたいマシンの空き情報をチェック＆予約
        </p>
      </li>
      <li class='list'>
        <%= image_tag "step02.jpg", class:"list-pict" %>
        <span class='step-list-number'>2</span>
        <h3 class='step-list-text'>
          時間に合わせてジムへ
        </h3>
        <p class='step-list-description'>
          マシンが空く時間に合わせてジムへGO！！
        </p>
      </li>
      <li class='list'>
        <%= image_tag "step03.jpg", class:"list-pict" %>
        <span class='step-list-number'>3</span>
        <h3 class='step-list-text'>
          筋トレスタート！
        </h3>
        <p class='step-list-description'>
          待ち時間ゼロで筋トレ！
        </p>
      </li>
    </ul>
  </div>
  <%# MaSeenを使う3つのSTEP部分 %>

  <%# マシン一覧 %>
  <div class='item-contents'>
    <h2 class='title'>設置マシン一覧</h2>
    <ul class='item-lists'>

    <% @machines.each do |machine|%>
      <li class='list'>
        <%= link_to machine_path(machine.id), method: :get do %>
        <div class='item-img-content'>
          <%= image_tag machine.image, class: "item-img" %>
        </div>
        <div class='item-info'>
          <h3 class='item-name'>
            <%= machine.name %>
          </h3>
        </div>
        <% end %>
      <% if user_signed_in? && current_user.id == 1 %>
        <div class="status-change">
          <%= link_to '情報の編集', edit_machine_path(machine.id), method: :get, class: "status-change-btn"%>
        </div>
      <% end %>
        <div class="machine-use-status">
          利用状況
        </div>
        <div class='status-btn'>
          <% if machine.status_id == 1 %>
            <span class='status-blue-text'>空</span>
          <% else %>
            <span class='status-red-text'>満</span>
          <% end %>
        </div>
        
        <% if machine.status_id == 2 %>  
          <div class='time-info'>
            <h3 class='time-text'>
             終了予定時刻　<%= machine.time %>
            </h3>
            <% unless machine.subscriber.blank? %> 
              <h3 class='time-text'>
              次回予約者　<%= machine.subscriber %>
              </h3>
            <% else %>
              <h3 class='time-text'>
              次回予約者無し
              </h3>
            <% end %>
          </div>
        <% end %>
      </li>
    <% end %>
  </div>
  <%# /マシン一覧 %>
</div>

<%= render "shared/footer" %>

app/views/machines/new.html.erb
<div class="new-items-contents">
  <header class="new-items-header">
    <%= link_to image_tag('maseen-logo-02.png' , size: '185x50'), "/" %>

  </header>
  <div class="new-items-main">
    <h2 class="new-items-title">新規マシン情報入力</h2>

    <%= form_with model: @machine, url: machines_path, local: true do |f| %>

    <%= render 'shared/error_messages', model: f.object %>

    <%# マシン画像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        マシン画像
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"item-image" %>
      </div>
    </div>
    <%# /マシン画像 %>

    <%# マシン名とマシン詳細 %>
    <div class="new-items">
      <div class="weight-bold-text">
        マシン名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :name, class:"items-text", id:"item-name", placeholder:"商品名（必須 40文字まで)", maxlength:"40" %>
      
      <div class="weight-bold-text">
        マシンの空き状況
      </div>
      <%= f.collection_select(:status_id, Status.all, :id, :name, {}, {class:"select-box", id:"machine-status"}) %>

      <div class="items-explain">
        <div class="weight-bold-text">
          マシンの詳細
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :detail, class:"items-text", id:"item-info", placeholder:"商品の説明（必須 1,000文字まで）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。" ,rows:"7" ,maxlength:"1000" %>
      </div>
    </div>
    <%# /マシン名とマシン詳細 %>

    <%# 下部ボタン %>
    <div class="sell-btn-contents">
      <%= f.submit "登録する" ,class:"sell-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>
  <footer class="new-items-footer">  
  </footer>
</div>

app/views/machines/show.html.erb
<%= render "shared/header" %>

<%# マシンの概要 %>
<div class="item-show">
  <div class="item-box">
    <h2 class="name">
      <%= @machine.name %>
    </h2>
    <div class='item-img-content'>
      <%= image_tag @machine.image ,class:"item-box-img" %>
      <%# 商品が売れている場合は、sold outを表示しましょう %>
      <%# <div class='sold-out'> %>
        <%# <span>Use In!!</span> %>
      <%# </div> %>
      <%# //商品が売れている場合は、sold outを表示しましょう %>
    </div>
        <div class="machine-use-status">
          利用状況
        </div>
        <div class='status-btn'>
          <% if @machine.status_id == 1 %>
            <span class='status-blue-text'>空</span>
          <% else %>
            <span class='status-red-text'>満</span>
          <% end %>
        </div>
        
        <% if @machine.status_id == 2 %>  
          <div class='time-info'>
            <h3 class='time-text'>
             終了予定時刻　<%= @machine.time %>
            </h3>
            <% unless @machine.subscriber.blank? %> 
              <h3 class='time-text'>
              次回予約者　<%= @machine.subscriber %>
              </h3>
            <% else %>
              <h3 class='time-text'>
              次回予約者無し
              </h3>
            <% end %>
          </div>
        <% end %>
    
    <% if user_signed_in? %>
      <% if current_user.id == 1 %>
        <%= link_to '情報の編集', edit_machine_path(@machine.id), method: :get, class: "item-red-btn" %>
        <%= link_to '削除', machine_path(@machine.id), method: :delete, class:'item-destroy' %>
      <% end %>
      <% if current_user.id != 1 && @machine.status_id == 2 %>
        <% if @machine.subscriber.blank? %>
          <%= link_to '予約画面に進む', edit_machine_path(@machine.id), method: :get, class:"item-red-btn" %>
        <% end %>
        <% if @machine.subscriber.present? && @machine.subscriber == current_user.nickname %>
          <%= link_to '予約を取り消す', edit_machine_path(@machine.id), method: :get, class:"item-red-btn" %>
        <% end %>
      <% end %> 
    <% end %>
    <%# //マシンが予約されていない場合はこちらを表示しましょう %>

    <div class="item-explain-box">
      <span><%= @machine.detail %></span>
    </div>
  <%# /マシンの概要 %>

</div>

<%= render "shared/footer" %>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<div class='footer'>
  <%= link_to image_tag("maseen-white-logo.png", class:"logo-white"), "#" %>
  <p>© MaSeen</p>
</div>

app/views/shared/_header.html.erb
<%# CSS・・・assets/stylesheets/shared/header.css %>
<header class='top-page-header'>
  <div class='nav'>
    <%= link_to image_tag("maseen-logo.png", class:"maseen-icon"), "/" %>
    <ul class='lists-right'>
      <% if user_signed_in? %>
        <li class="user-nickname"><%= current_user.nickname %> </li>
        <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %> </li>
        <% if current_user.id == 1 %>
          <li><%= link_to '新規マシン登録', "/machines/new", class: "new-machine" %> </li>
        <%end%>
      <% else %>
        <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
        <li><%= link_to '新規ユーザー登録',new_user_registration_path, class: "sign-up" %></li>
      <% end %>
    </ul>
  </div>
</header>

app/views/shared/_second-footer.html.erb
<footer class='second-fotter'>
</footer>

app/views/shared/_second-header.html.erb
<header class='second-header'>
  <%= link_to image_tag("maseen-logo-02.png", class:"second-logo"), "/" %>
</header>